---
title: "Untitled"
author: "Kah Meng Soh"
date: "2/6/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r fig.height=7.5,fig.width=7.5}
data=read.table("http://www.stat.umn.edu/~gary/book/fcdae.data/ex13.5",header=TRUE)
attach(data)
names(data)
operator=as.factor(operator)
machine=as.factor(machine)
day=as.factor(day)
trt=as.factor(trt)
m=lm(y~day+operator+machine+trt)
par(mfrow = c(2,2))
plot(m)
#As we can see, the zig-zag shape on residual plot indicate presence of non-linearity hence model error, we can try boxcox transformation and see how it goes.
library(MASS)
bc=boxcox(m)
i=which.max(bc$y)
bc$x[i]
#Boxcox suggested power of 2 transformation.
m=lm(y^2~day+operator+machine+trt)
plot(m)
#Boxcox transformation doesn't help, therefore we can assume that there's some model error in the mean function and we shouldn't trust the p-value from the model. 
anova(m)
#P-value for trt is 0.1099>0.05, hence no evidence that the treatment are significant difference
```
