---
title: "Untitled"
author: "Kah Meng Soh"
date: '2022-04-21'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# Question 1
#1a
library(nlme)
options(contrasts = c("contr.sum", "contr.poly"))
head(Oxboys)
m1.lme = lme(height~age+I(age^2), data = Oxboys, random = ~1|Subject)
getVarCov(m1.lme, type = 'random.effects')
getVarCov(m1.lme, individual = 1, type = 'conditional')
#The model has only intercept as random effect, therefore the 1D variance structure for the intercept random effect; σˆA=8.0975.
#As the default within subject error structure is chosen to be the Λ=σ^2I=σhat=1.281
getVarCov(m1.lme, individual = 1, type = 'marginal')
intervals(m1.lme)

#1b
m2.lme = lme(height~age+I(age^2), data = Oxboys, random = ~age+I(age^2)|Subject, correlation = corAR1())
sigma_2d = getVarCov(m2.lme, type = 'random.effects')
sigma_2d
sigma_2_lambda = getVarCov(m2.lme, type = 'conditional')
sigma_2_lambda
rho = 0.079844/0.29142
rho
#sigma_2 = 0.29142
d_hat = sigma_2d/0.29142
d_hat
getVarCov(m2.lme, type = 'marginal')

#1c
m1.lme = lme(height~age+I(age^2), data = Oxboys, random = ~1|Subject)
m2.lme = lme(height~age+I(age^2), data = Oxboys, random = ~age|Subject)
m3.lme = lme(height~age+I(age^2), data = Oxboys, random = ~age+I(age^2)|Subject)
anova(m1.lme, m2.lme, m3.lme)

#(1) Yes, age should be included with a subject specific random slope
#(2) Yes

#1d
m4.lme = lme(height~age+I(age^2), data = Oxboys, random = ~age+I(age^2)|Subject)
m5.lme = lme(height~age+I(age^2), data = Oxboys, random = ~age+I(age^2)|Subject, correlation = corAR1())
m6.lme = lme(height~age+I(age^2), data = Oxboys, random = ~age+I(age^2)|Subject, correlation = corAR1())
anova(m4.lme, m5.lme)
anova(m4.lme, m6.lme)
#AR1 correlation structure is better among the other two.

#1e
plot(m5.lme)
qqnorm(m5.lme)
qqnorm(m5.lme, form=~ranef(.), id=0.1)
#There is no sign of non-constant variance. The fixed and random effects are approximately normal.
```

```{r}
# Question 2
#2a
traffic = read.table('http://www.stat.umn.edu/~gary/book/fcdae.data/pr16.8', header = T)
traffic = within(traffic, {sign = as.factor(sign)
timing = as.factor(timing)
interchange = as.factor(interchange)})
head(traffic)
m = aov(speed~timing*sign+Error(interchange:sign), data = traffic)
summary(m)
# Only time effect significant, sign is the whole plot unit, timing is the split plot units, WP treatments are signs and no signs, SP treatments are 3 timings 0, 3 and 6 seconds.

#2b
m.lme = lme(speed~sign*timing, data = traffic, random= ~1|interchange/sign)
anova(m.lme)
#Group is sign nested in interchange, the measure that is repeated within group is the timings of the traffic lights in each sign nested within interchange.The results from anova are similar to that of lme.

#2c
library(lme4)
m.lmer = lmer(speed~sign*timing + (1|interchange/sign), data = traffic )
anova(m.lmer)
# Results of lme and lmer are identical

#2d
library(gmodels)
fit.contrast(m.lme, varname = 'timing', coef = rbind(c(1,-1,0), c(1,0,-1)), conf.int = .95)
fit.contrast(m.lme, varname = 'timing', coef = c(0, 1, -1), conf.int = .95)
```

```{r}
#Question 3
#3a
soy = read.table('http://www.stat.umn.edu/~gary/book/fcdae.data/pr13.5', header = T)
soy = within(soy, {year.loc = as.factor(year.loc)
rotation = as.factor(rotation)
variety = as.factor(variety)})
head(soy)
summary(aov(y~year.loc+rotation*variety, data = soy))
# Rotation is significant

#3b
m.lme = lme(y~rotation*variety, random= ~1|year.loc, data = soy)
anova(m.lme)
m.lmer = lmer(y~rotation*variety + (1|year.loc), data = soy)
anova(m.lmer)
# Results are identical to that of lm().
```

```{r}
#Question 4
#4a
library(faraway)
library(ggplot2)
library(car)
breaking = within(breaking, {operator = as.factor(operator)
day = as.factor(day)
supplier = as.factor(supplier)})
head(breaking)
ggplot(data=breaking, aes(x=operator, y=y, shape = day, color=supplier)) + geom_point()
par(mfrow = c(1,3))
plot(breaking$operator, breaking$y)
plot(breaking$day, breaking$y)
plot(breaking$supplier, breaking$y)
#Operator 2 has the highest breaking strength on day2 by supplier C.
#Operator 1 has a higher median breaking strength compared to other operators, Supplier C has a much higher median breaking strength than other suppliers.
#The effect of supplier is much more prominent as we can see there is a huge difference between the distribution of breaking strengths between the suppliers.

#4b
m = lm(y~operator+day+supplier, data = breaking)
anova(m)
library(lmerTest)
m.lmer = lmerTest::lmer(y~supplier+(1|operator)+(1|day), data = breaking, REML=T)
#supplier is significant main effect
anova(m.lmer, type = 2)
## Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
summary(m.lmer)
library(emmeans)
#As the variables that we block are the major sources of variation in the experiment which make them random in nature, hence the operator and days are a natural choice for random effects.
emmeans(m.lmer, specs = ~supplier)
ggplot(data=breaking, aes(x=operator, y=y, color=day)) + geom_point()
# Supplier C has the highest breaking point which can also be seen in the boxplot above
# As we can see, the breaking point varies non-linearly for a fixed operator when the days are varied and vice versa. This implies the variation between operators and days is non-linear.

#4d
m.lmerd = lmerTest::lmer(y~supplier+(1|day), data = breaking, REML=T)
m.lmero = lmerTest::lmer(y~supplier+(1|operator), data = breaking, REML=T)
library(RLRsim)
exactRLRT(m.lmero, m.lmer, m.lmerd)#test for operator random effect
exactRLRT(m.lmerd, m.lmer, m.lmero)#test for day random effect
#Day, Operator significant

#4e
library(pbkrtest)
m.lmer1 = lmerTest::lmer(y~1+(1|operator)+(1|day), data = breaking, REML = F)
KRmodcomp(m.lmer1, m.lmer)
# Supplier is significant

#4f
m.lme.final = lme(y~supplier, , data = breaking, random = list(~1|operator, ~1|day))
new_d = data.frame(operator= c("op3", "op4", "op2", "op1", "op3"),
day = c("day1", "day3", "day4", "day3", "day2"),
supplier = c("C", "C", "C", "C", "C"))
new_d = within(new_d, {operator = as.factor(operator)
day = as.factor(day)
supplier = as.factor(supplier)})
results = predict(m.lme.final, new_d)
length(results[results<1000])/5
# For 5 values for the highest choice of supplier, the proportion is close to 40%.
```
```{r}
#Question 5
# WPU = Pesticide; WP Trt = P1, P2, P3
# SPU = Irrigation; SP Trt = Irrigation and No Irrigation
# SSPU = Variety, SSP Trt = Variety 1 and Variety 2
```
