---
title: "Untitled"
author: "Kah Meng Soh"
date: "2/6/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r fig.height=7.5,fig.width=7.5}
data=read.table("http://www.stat.umn.edu/~gary/book/fcdae.data/ex6.3",header=TRUE)
attach(data)
drug=as.factor(drug)
m=lm(dose~drug)
anova(m)
summary(m)
par(mfrow=c(2,2))
plot(m)
#From the residual vs fitted, the slope is horizontal with some part slanted, therefore I believe the error variance to be equal, and from the Normal Q-Q plot, many points are on the straight line, therefore I believe that error follows normality assumption. Hence, we considered it valid to use ANOVA.
#Based on the treatment mean, the most effective drug is drug 4 and the least effective drug is drug 1
```
```{r fig.height=7.5,fig.width=7.5}
m=aov(dose ~ drug)
cis=TukeyHSD(m, which="drug", ordered=T, conf.level=0.95)
cis
```
```{r}
#Use MCB to find subset of treatments that are most similar to the most effective drug with an error rate of 0.05.
m=lm(dose~drug)
anova(m)
k=4-1
nu=40-4
smallest_trt_mu=7.41
dunnet_crit_value=2.13
se=sqrt(8.97/5)
best_cutoff=smallest_trt_mu+dunnet_crit_value*se
best_cutoff
#All treatments with group mean less than 10.26 will be in the 95%  best subset grouping, so drug 2,3,4 are less than the cutoff value, so they are the best subset which cannot be distinguished from the most effective drug.
```